config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, only: [:index, :show] do
    resources :albums
  end
  resources :reviews do
    resources :comments
  end

  root to: "albums#index"

end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user
    accepts_nested_attributes_for :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to: review
    belongs_to: user
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    has_many :comments, through: :users
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  has_many :albums
  has_many :reviews, through: :albums
  has_many :comments, through: :reviews
  
  def self.from_omniauth(auth)
    # Either create a User record or update it based on the provider (Google) and the UID   
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_album, only: [:show, :edit]
    before_filter :set_user

    def index
        @albums = Album.all
    end

    def new
        @album = Album.new
        @album.build_user
    end

    def show
        @album = Album.find(params[:user_id])
    end

    def create
        @album = current_user.albums.build(album_params)
        respond_to do |format|
            if @album.save
                format.html {redirect_to @user, @album, notice: 'Album was successfully created.'}
            else
                format.html {render :new}
            end
        end
    end

private

    def set_user
        @user = User.find(params[:user_id])
    end

    def set_album
        @album = Album.find(params[:id])
    end

    def album_params
        params.require(:album).permit(:artist, :title, user_attributes: [:name])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/omniauth_callbacks_controllers.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  #  def google_oauth2
   #   @user = User.from_omniauth(request.env["omniauth.auth"])
    #if @user.persisted?
     #   sign_in @user, :event => :authentication #this will throw if @user is not activated
    #    set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
     # else
    #    session["devise.google_data"] = request.env["omniauth.auth"]
   #   end
    #  redirect_to '/'
   # end

    private
    def sign_up_params 
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def index
        @reviews = Review.all
    end
    def new
        @review = Review.create
    end
    def show
        @review = Review.find(params[:id])
    end
end

app/controllers/users/omniauth_callbacks_controllers.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in @user, :event => :authentication #this will throw if @user is not activated
            set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
        else
            session["devise.google_data"] = request.env["omniauth.auth"]
        end
            redirect_to '/'
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_for( :album, :html => {:class => "form-horizontal", :role => "form"}, url: new_user_album_url) do |f| %>
  <%= f.label :artist %>
  <%= f.text_field :artist%>
        <br><br>
  <%= f.label :title %>
  <%= f.text_field :title %>
        <br><br>
  <%= f.submit %>
<% end %>

app/views/albums/index.html.erb
<h1>Albums</h1>
	<p>
    Artist<br>
	Title
    </p><br>
	<% @albums.each do |album| %>
	    <%= album.artist %>
	    <%= album.title %>
	    <%= link_to 'Show', album %>
	    <%= link_to 'Edit', edit_user_album_path(album) %>
	    <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %>
	    <% end %>

app/views/albums/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</html>

app/views/reviews/index.html.erb
<%= link_to reviews_path %>

app/views/reviews/new.html.erb
<%= form_for @review do |f| %>
   <br><%= f.label :title %>
    <br><%= f.text_field :title %>
    <br><%= f.label :date %>
    <br><%= f.date_select :date %>
    <br><%= f.label :content %>
    <br><%= f.text_area :content, :size => "60x12" %>
    <br><%= submit_tag "Create" %>
<% end %>

app/views/users/index.html.erb
<%= link_to "New review", new_review_path %>
<% @users.each do |user| %>
    <%= user.name %>
    <%= user.reviews %>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>